version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - dupl
          - gocognit
          - unparam
          - noctx
          - revive
formatters:
  enable:
    - gofmt
    - goimports
